In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/public_school_data.csv', skiprows=6)
df.head(3)

,School Name,State Name [Public School] Latest available year,School ID (12-digit) - NCES Assigned [Public School] Latest available year,Black or African American Students [Public School] 2024-25,Black or African American Students [Public School] 2023-24,Black or African American Students [Public School] 2022-23,Black or African American Students [Public School] 2021-22,Black or African American Students [Public School] 2020-21,Black or African American Students [Public School] 2019-20,Black or African American Students [Public School] 2018-19,...,Free and Reduced Lunch Students [Public School] 2017-18,Free and Reduced Lunch Students [Public School] 2016-17,Free and Reduced Lunch Students [Public School] 2015-16,Free and Reduced Lunch Students [Public School] 2014-15,Free and Reduced Lunch Students [Public School] 2013-14,Free and Reduced Lunch Students [Public School] 2012-13,Free and Reduced Lunch Students [Public School] 2011-12,Free and Reduced Lunch Students [Public School] 2010-11,Free and Reduced Lunch Students [Public School] 2009-10,Free and Reduced Lunch Students [Public School] 2008-09
0,'O ME-NOK LEARNING CENTER,California,6.107700e+10,0,0,0,–,–,0,–,...,58,102,77,90,68,67,‡,80,82,97
1,1 LT CHARLES W. WHITCOMB SCHOOL,Massachusetts,2.507320e+11,60,45,40,33,42,44,46,...,–,–,–,717,687,654,618,613,561,490
2,100 BLACK MEN OF THE BAY AREA COMMUNITY,California,6.280501e+10,†,†,†,†,†,†,†,...,†,†,†,†,47,18,†,†,†,†

In [3]:
hispanic = pd.read_csv('../data/raw/hispanic_students_data.csv', skiprows=6)
hispanic.head(3)

,School Name,State Name [Public School] Latest available year,School ID (12-digit) - NCES Assigned [Public School] Latest available year,Hispanic Students [Public School] 2024-25,Hispanic Students [Public School] 2023-24,Hispanic Students [Public School] 2022-23,Hispanic Students [Public School] 2021-22,Hispanic Students [Public School] 2020-21,Hispanic Students [Public School] 2019-20,Hispanic Students [Public School] 2018-19,Hispanic Students [Public School] 2017-18,Hispanic Students [Public School] 2016-17,Hispanic Students [Public School] 2015-16,Hispanic Students [Public School] 2014-15,Hispanic Students [Public School] 2013-14,Hispanic Students [Public School] 2012-13,Hispanic Students [Public School] 2011-12,Hispanic Students [Public School] 2010-11,Hispanic Students [Public School] 2009-10,Hispanic Students [Public School] 2008-09
0,'O ME-NOK LEARNING CENTER,California,6.107700e+10,10,13,14,11,10,8,8,6,5,8,8,6,9,10,12,8,5
1,1 LT CHARLES W. WHITCOMB SCHOOL,Massachusetts,2.507320e+11,641,611,645,631,626,807,732,648,592,540,522,506,457,429,439,409,397
2,100 BLACK MEN OF THE BAY AREA COMMUNITY,California,6.280501e+10,†,†,†,†,†,†,†,†,†,†,†,2,2,†,†,†,†

In [4]:
df = df.merge(
    hispanic, 
    on=[
        'School ID (12-digit) - NCES Assigned [Public School] Latest available year',
        'School Name',
        'State Name [Public School] Latest available year'
    ], 
    how='left'
)

In [5]:
schools_info = df.loc[:, 
    ["School ID (12-digit) - NCES Assigned [Public School] Latest available year",
    "School Name", "State Name [Public School] Latest available year"]
]

schools_columns = {
    "School ID (12-digit) - NCES Assigned [Public School] Latest available year" : "school_id",
    "School Name": "school_name",
    "State Name [Public School] Latest available year": "state_name"
}

schools_info = schools_info.rename(columns=schools_columns)
schools_info['school_id'] = schools_info['school_id'].astype(str)
schools_info.head(2)

        school_id                      school_name     state_name
0   61077001195.0        'O ME-NOK LEARNING CENTER     California
1  250732002639.0  1 LT CHARLES W. WHITCOMB SCHOOL  Massachusetts

In [7]:
school_years = [
    '2008-09', '2009-10', '2010-11', '2011-12',
    '2012-13', '2013-14', '2014-15', '2015-16',
    '2016-17', '2017-18', '2018-19', '2019-20',
    '2020-21', '2021-22', '2022-23', '2023-24',
    '2024-25'
]

slices = []
for school_year in school_years:
    columns = {
        "School ID (12-digit) - NCES Assigned [Public School] Latest available year": "school_id",
        f"White Students [Public School] {school_year}": "white_students",
        f"Black or African American Students [Public School] {school_year}": "black_students",
        f"Hispanic Students [Public School] {school_year}": "hispanic_students",
        f"Total Race/Ethnicity [Public School] {school_year}": "total_students",
        f"Free and Reduced Lunch Students [Public School] {school_year}": "free_and_reduced_lunch"
    }
    df_slice = df.loc[:, columns.keys()]
    df_slice = df_slice.rename(columns=columns)
    df_slice["school_year"] = school_year
    slices.append(df_slice)

racial_data = pd.concat(slices, ignore_index=True)
racial_data.head(2)

,school_id,white_students,black_students,hispanic_students,total_students,free_and_reduced_lunch,school_year
0,6.107700e+10,33,0,5,114,97,2008-09
1,2.507320e+11,859,40,397,1345,490,2008-09